#!/usr/bin/env python3
"""Build the Webflow-safe Home slides embed from home-slides.html.

The Webflow Embed element stays below its size limit by loading the generated
CSS and JavaScript as public GitHub Pages assets. The HTML remains the copyable
artifact listed in embeds.html.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "home-slides.html"
OUT_HTML = ROOT / "embed/home-slides-embed.html"
OUT_CSS = ROOT / "embed/home-slides-embed.css"
OUT_JS = ROOT / "embed/home-slides-embed.js"
PUBLIC_BASE = "https://stanislavaki.github.io/birch-ai"
VERSION = "20260916"

STATE_CLASSES = (
    "is-active",
    "is-blinking",
    "is-closed",
    "is-core",
    "is-done",
    "is-down",
    "is-dragging",
    "is-forced",
    "is-gone",
    "is-guides",
    "is-in",
    "is-intro",
    "is-lit",
    "is-live",
    "is-on",
    "is-stacked",
    "is-visible",
)

ID_MAP = {
    "card": "hse-card",
    "canvas": "hse-canvas",
    "coreBox": "hse-core-box",
    "hsAnswerA": "hse-answer-a",
    "hsAnswerB": "hse-answer-b",
    "hsBubble": "hse-bubble",
    "hsCursor": "hse-cursor",
    "hsPlaceholder": "hse-placeholder",
    "hsResponse": "hse-response",
    "hsSend": "hse-send",
    "hsTools": "hse-tools",
    "hsTyped": "hse-typed",
    "hsUsed": "hse-used",
    "hsUsedRow": "hse-used-row",
    "phA": "hse-phone-answer",
    "phGreet": "hse-phone-greeting",
    "phKb": "hse-phone-keyboard",
    "phKeys": "hse-phone-keys",
    "phMsg": "hse-phone-message",
    "phQ": "hse-phone-question",
    "phScroll": "hse-phone-scroll",
    "phTyped": "hse-phone-typed",
    "phTypedText": "hse-phone-typed-text",
}


def extract_between(text: str, start: str, end: str, offset: int = 0) -> str:
    start_index = text.index(start, offset) + len(start)
    end_index = text.index(end, start_index)
    return text[start_index:end_index]


def rename_local_symbols(text: str) -> str:
    replacements = (
        ("chat-card", "hse-chat-card"),
        ("cursorBlink", "hse-cursor-blink"),
        ("hs-no-anim", "hse-no-anim"),
        ("hsm__", "hse-hsm__"),
        ("hs__", "hse-hs__"),
        ("hs-blink", "hse-blink"),
        ("hs-ring", "hse-ring"),
        ("hs-caret", "hse-caret"),
        ("--ring-angle", "--hse-ring-angle"),
    )
    for old, new in replacements:
        text = text.replace(old, new)
    text = re.sub(r"--in\b", "--hse-in", text)
    for name in STATE_CLASSES:
        text = re.sub(rf"\b{re.escape(name)}\b", f"hse-{name}", text)
    return text


def strip_css_comments(text: str) -> str:
    return re.sub(r"/\*.*?\*/", "", text, flags=re.S)


def strip_html_comments(text: str) -> str:
    return re.sub(r"<!--.*?-->", "", text, flags=re.S)


def ascii_html(text: str) -> str:
    return "".join(ch if ord(ch) < 128 else f"&#x{ord(ch):X};" for ch in text)


def ascii_javascript(text: str) -> str:
    out: list[str] = []
    for ch in text:
        code = ord(ch)
        if code < 128:
            out.append(ch)
        elif code <= 0xFFFF:
            out.append(f"\\u{code:04x}")
        else:
            code -= 0x10000
            out.append(f"\\u{0xD800 + (code >> 10):04x}\\u{0xDC00 + (code & 0x3FF):04x}")
    return "".join(out)


def ascii_css(text: str) -> str:
    return "".join(ch if ord(ch) < 128 else f"\\{ord(ch):X} " for ch in text)


def build_css(source: str) -> str:
    source_css = extract_between(source, "<style>", "</style>")
    source_css = source_css.replace(":root {", ".home-slides-e {", 1)
    source_css = re.sub(r"\.hs(?=[\s,{:#>])", ".hse-hs", source_css)
    source_css = re.sub(r"\.hsm(?=[\s,{:#>])", ".hse-hsm", source_css)
    source_css = rename_local_symbols(source_css)
    source_css = source_css.replace(".hse-hs__sticky > .container", ".hse-hs__sticky > .hse-container-e")
    source_css = source_css.replace(".container.hse-hsm", ".hse-container-e.hse-hsm")
    source_css = re.sub(r"\.btn\b", ".hse-btn", source_css)
    source_css = source_css.replace("var(--nav-height)", "var(--nav-height, 0px)")
    source_css = source_css.replace("url(images/", f"url({PUBLIC_BASE}/images/")
    source_css = re.sub(
        r"(\.hse-hs\s*\{[^{}]*?)padding-block:\s*var\([^;]+;",
        r"\1padding-block: 0;",
        source_css,
        flags=re.S,
    )
    source_css = strip_css_comments(source_css)

    button_css = (ROOT / "design-system/components/button.css").read_text()
    button_css = button_css.replace(".btn", ".hse-btn")
    button_css = strip_css_comments(button_css)

    chat_css = (ROOT / "design-system/components/chat-card.css").read_text()
    chat_css = rename_local_symbols(chat_css)
    chat_css = strip_css_comments(chat_css)

    prelude = """
/* Generated from home-slides.html. Do not edit this file directly. */
.home-slides-e {
  --font: "TT Commons Pro Variable", "Inter", Arial, sans-serif;
  --color-primary: #FFE243;
  --color-accent-green: #04DE00;
  --color-accent-pink: #FF21A6;
  --color-accent-blue: #1877F2;
  --color-accent-light-blue: #59DBFF;
  --color-accent-purple: #5B45CD;
  --color-text: #FFFFFF;
  --color-text-inverted: #000000;
  --color-text-grey: #909090;
  --text-h5-size: 1.2rem;
  --text-h5-lh: 1.2;
  --text-h5-ls: 0em;
  --text-body-size: 0.9rem;
  --text-body-lh: 1.2;
  --text-body-ls: 0em;
  --text-btn-size: 1.5rem;
  --text-btn-lh: 1;
  --text-btn-ls: -0.02em;
  --text-btn-xs-size: 0.9rem;
  --space-sm: 1rem;
  --space: 1.5rem;
  --space-md: 2rem;
  --space-lg: 3rem;
  --space-xl: 5rem;
  --gap-sm: 0.5rem;
  --gap-main: 1rem;
  --gap-md: 1.5rem;
  --pad-card: 1.5rem;
  --btn-h-xs: 2.5rem;
  --btn-h-s: 6.25rem;
  --radius-sm: 0.5rem;
  --radius-lg: 1rem;
  --radius-xl: 1.5rem;
  --radius-pill: 9999px;
  width: 100%;
  position: relative;
  font-family: var(--font);
  font-weight: 600;
  -webkit-font-smoothing: antialiased;
  /* no background - comes from Webflow */
}
.home-slides-e,
.home-slides-e *,
.home-slides-e *::before,
.home-slides-e *::after { box-sizing: border-box; }
.home-slides-e img,
.home-slides-e svg { display: block; max-width: 100%; }
.home-slides-e a { color: inherit; text-decoration: none; }
.home-slides-e button { font: inherit; cursor: pointer; border: 0; background: none; padding: 0; }
.home-slides-e .hse-container-e {
  width: 100%;
  max-width: 1280px;
  margin-inline: auto;
  padding-inline: 0;
  font-size: 16px;
}
.home-slides-e .hse-t-h5 {
  font-family: var(--font);
  font-size: var(--text-h5-size);
  line-height: var(--text-h5-lh);
  letter-spacing: var(--text-h5-ls);
  font-weight: 600;
}
.home-slides-e .hse-t-body {
  font-family: var(--font);
  font-size: var(--text-body-size);
  line-height: var(--text-body-lh);
  letter-spacing: var(--text-body-ls);
  font-weight: 600;
}
"""
    css = prelude + "\n" + button_css + "\n" + chat_css + "\n" + source_css
    css = re.sub(r"[ \t]+\n", "\n", css)
    css = re.sub(r"\n{3,}", "\n\n", css)
    return ascii_css(css).strip() + "\n"


def build_html(source: str) -> str:
    start = source.index('<section class="section hs" id="hs">')
    script_start = source.index("\n<script>", start)
    html = source[start:script_start]
    html = html.replace(
        '<section class="section hs" id="hs">',
        '<div class="home-slides-e hse-hs" data-hse-root>',
        1,
    )
    close = html.rfind("</section>")
    html = html[:close] + "</div>" + html[close + len("</section>") :]
    html = rename_local_symbols(html)
    html = html.replace('class="container hsm"', 'class="container hse-hsm"')
    html = re.sub(r"\bcontainer\b", "hse-container-e", html)
    html = re.sub(r"\bbtn\b", "hse-btn", html)
    html = re.sub(r"\bt-h5\b", "hse-t-h5", html)
    html = re.sub(r"\bt-body\b", "hse-t-body", html)
    for old, new in ID_MAP.items():
        html = html.replace(f'id="{old}"', f'id="{new}"')
    html = html.replace('href="#">Explore integrations', 'href="/integrations">Explore integrations')
    html = html.replace('href="#">More about Rules', 'href="/manage">More about Rules')
    html = html.replace('href="#">See how it thinks', 'href="/ai">See how it thinks')
    html = html.replace('href="#">More about Birch AI', 'href="/ai">More about Birch AI')
    html = html.replace('href="#">Explore MCP', 'href="/mcp">Explore MCP')
    html = html.replace('href="#">More about MCP', 'href="/mcp">More about MCP')
    html = re.sub(r'(?<=src=")images/', f"{PUBLIC_BASE}/images/", html)
    html = html.replace("url(images/", f"url({PUBLIC_BASE}/images/")
    html = strip_html_comments(html)
    html = re.sub(r"\n\s*\n", "\n", html).strip()

    header = f"""<!--
  BIRCH HOME SLIDES - WEBFLOW EMBED
  Placement: Home page, immediately after the Trusted by block.
  Webflow owns the outer Section and Container. Keep ancestor overflow visible.
  CSS and JS are versioned public assets generated from home-slides.html.
-->
<link rel="stylesheet" href="{PUBLIC_BASE}/embed/home-slides-embed.css?v={VERSION}">
"""
    footer = f'\n<script src="{PUBLIC_BASE}/embed/home-slides-embed.js?v={VERSION}"></script>\n'
    return ascii_html(header + html + footer)


def build_js(source: str) -> str:
    section_start = source.index('<section class="section hs" id="hs">')
    script_open = source.index("<script>", section_start)
    script = extract_between(source, "<script>", "</script>", script_open)
    script = rename_local_symbols(script)
    for old, new in ID_MAP.items():
        script = script.replace(f"'{old}'", f"'{new}'")

    script = script.replace(
        "  var track  = document.getElementById('hs');\n"
        "  var sticky = track.querySelector('.hse-hs__sticky');\n"
        "  var card   = document.getElementById('hse-card');\n"
        "  var canvas = document.getElementById('hse-canvas');\n"
        "  var bars   = [].slice.call(track.querySelectorAll('.hse-hs__bar'));\n"
        "  var root   = document.documentElement;",
        "  var track  = embedRoot;\n"
        "  var sticky = track.querySelector('.hse-hs__sticky');\n"
        "  var card   = track.querySelector('#hse-card');\n"
        "  var canvas = track.querySelector('#hse-canvas');\n"
        "  var bars   = [].slice.call(track.querySelectorAll('.hse-hs__bar'));\n"
        "  var docRoot = document.documentElement;\n"
        "  if (!sticky || !card || !canvas) return;\n\n"
        "  function rootFontPx() {\n"
        "    return parseFloat(getComputedStyle(docRoot).fontSize) || 16;\n"
        "  }\n"
        "  function navHeightPx() {\n"
        "    var raw = getComputedStyle(docRoot).getPropertyValue('--nav-height').trim();\n"
        "    if (!raw) return 0;\n"
        "    var value = parseFloat(raw);\n"
        "    if (!isFinite(value)) return 0;\n"
        "    if (/px$/i.test(raw)) return value;\n"
        "    return value * rootFontPx();\n"
        "  }",
    )
    script = script.replace("document.querySelectorAll('[data-hsm-drag]')", "track.querySelectorAll('[data-hsm-drag]')")
    script = script.replace("document.querySelector('[data-hsm-chat]')", "track.querySelector('[data-hsm-chat]')")
    script = script.replace("document.querySelector('[data-hsm-phone]')", "track.querySelector('[data-hsm-phone]')")
    script = re.sub(
        r"document\.getElementById\('([^']+)'\)",
        lambda match: f"track.querySelector('#{match.group(1)}')",
        script,
    )

    script = script.replace(
        "    var cs = getComputedStyle(root), rootPx = parseFloat(cs.fontSize);\n"
        "    root.style.setProperty('--bar-h', '0rem');",
        "    var cs = getComputedStyle(track), rootPx = rootFontPx();\n"
        "    track.style.setProperty('--bar-h', '0rem');",
    )
    script = script.replace("    root.style.setProperty('--bar-h',", "    track.style.setProperty('--bar-h',")
    script = script.replace(
        "    var navH  = parseFloat(cs.getPropertyValue('--nav-height')) * rootPx;",
        "    var navH  = navHeightPx();",
    )
    script = script.replace("    root.style.setProperty('--slide-gap-bottom',", "    track.style.setProperty('--slide-gap-bottom',")
    script = script.replace(
        "    var cs = getComputedStyle(root);\n"
        "    var navH = parseFloat(cs.getPropertyValue('--nav-height')) * parseFloat(cs.fontSize);",
        "    var navH = navHeightPx();",
    )
    script = script.replace(
        "      var cs = getComputedStyle(root), navH = parseFloat(cs.getPropertyValue('--nav-height')) * parseFloat(cs.fontSize);\n"
        "      window.scrollTo({ top: track.offsetTop - navH + span * (r[0] / TOTAL) + 1, behavior: 'smooth' });",
        "      var navH = navHeightPx();\n"
        "      var trackTop = track.getBoundingClientRect().top + window.pageYOffset;\n"
        "      var docStyle = docRoot.style;\n"
        "      var previous = docStyle.getPropertyValue('scroll-behavior');\n"
        "      var priority = docStyle.getPropertyPriority('scroll-behavior');\n"
        "      docStyle.setProperty('scroll-behavior', 'auto', 'important');\n"
        "      window.scrollTo({ top: trackTop - navH + span * (r[0] / TOTAL) + 1, behavior: 'auto' });\n"
        "      requestAnimationFrame(function () {\n"
        "        if (previous) docStyle.setProperty('scroll-behavior', previous, priority);\n"
        "        else docStyle.removeProperty('scroll-behavior');\n"
        "      });",
    )
    script = script.replace(
        "  new ResizeObserver(lockBarHeight).observe(document.body);",
        "  new ResizeObserver(lockBarHeight).observe(track);",
    )
    script = re.sub(r"\n\s*window\.__hs\s*=\s*\{[^;]+;", "", script)
    script = re.sub(r"\n\s*window\.__hsIntroReplay\s*=\s*function \(\) \{[^\n]+", "", script)
    script = re.sub(r"\n\s*window\.__hsApply\s*=\s*apply;", "", script)
    script = script.replace("  addEventListener('scroll',", "  window.addEventListener('scroll',")
    script = script.replace("  addEventListener('resize',", "  window.addEventListener('resize',")

    marker = "(function () {\n  'use strict';"
    script = script.replace(
        marker,
        marker
        + "\n\n  document.querySelectorAll('.home-slides-e:not([data-hse-ready])').forEach(function (embedRoot) {\n"
        + "    embedRoot.setAttribute('data-hse-ready', '');",
        1,
    )
    end = script.rfind("})();")
    script = script[:end] + "  });\n" + script[end:]
    return ascii_javascript(script).strip() + "\n"


def main() -> None:
    source = SOURCE.read_text()
    OUT_CSS.write_text(build_css(source))
    OUT_JS.write_text(build_js(source))
    OUT_HTML.write_text(build_html(source))
    print(f"Wrote {OUT_HTML.relative_to(ROOT)} ({OUT_HTML.stat().st_size} bytes)")
    print(f"Wrote {OUT_CSS.relative_to(ROOT)} ({OUT_CSS.stat().st_size} bytes)")
    print(f"Wrote {OUT_JS.relative_to(ROOT)} ({OUT_JS.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
